name: Be That Brand Flavor
favicon: null
layout_spectrum: 0.388676596339792
typography_spectrum: 0.46431372012011707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4393856511451304
  lightness: 0.8622965607792139
  saturation: 0.737242184812203
  rhythmicContrast: 0.6148640085011721
purpose: []
